### ISSUE TITLE
.vscode

### ISSUE THREAD

**Issue by LuisM95** [FernandaOchoa/python101Nubers#1]
## Carpeta .vscode

hola sherpa disculpe la pregunta no pude estar los dos lives de la semana pasada gentilmente podria explicarme el ejercicio de esta carpeta de antemano muchas gracias

**Comment by FernandaOchoa** [comment]
Hola esos son los archivos de configuración del ambiente de desarrollo.

La sesiones las puedes encontrar aquí:

[Sesión Introducción a la Programación con Python](https://web.microsoftstream.com/video/3ec20b6e-8d3b-466e-aa56-c1b160118194)

[Sesión de Conceptos de IA](https://web.microsoftstream.com/video/d5109b18-d867-4773-a10e-f79080d50b12)

[Sesión de las prácticas de la semana 1](https://web.microsoftstream.com/video/8f98bfff-26ea-4a2a-a6f3-35e7032dd2ea)
