### ISSUE TITLE
Error a agregar el paquetel dotnet add package Microsoft.CognitiveServices.Speech.Audio

### ISSUE THREAD

**Issue by EdwardBaruch** [FernandaOchoa/python101Nubers#2]
hola  sherpa t, lado de contabilidad tengo error al agregar el paquete dotnet add package Microsoft.CognitiveServices.Speech.Audio
agregue speach.csproj  al entorno posteriormente dotnet add package Microsoft.CognitiveServices.Speech

en coonsola me sale estoy en vscode de escritorio, no he podio que mesal bash en la consola de comando me sale cmd:1
el error que tengo es
```
info : Agregando PackageReference para el paquete "Microsoft.CognitiveServices.Speech.Audio" al proyecto "C:\Users\Hp\Documents\azure\speach\speach.csproj".
info : Restaurando paquetes para C:\Users\Hp\Documents\azure\speach\speach.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.cognitiveservices.speech.audio/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.cognitiveservices.speech.audio/index.json 323 ms
error: No se encuentra el paquete Microsoft.CognitiveServices.Speech.Audio. No existe ningún paquete con este id. en los orígenes: nuget.org
```
```
error: El paquete "Microsoft.CognitiveServices.Speech.Audio" no es compatible con los marcos de trabajo de "all" del proyecto "C:\Users\Hp\Documents\azure\speach\speach.csproj".
```

que puedo hacer

**Comment by FernandaOchoa** [comment]
Hola, ok intenta bajo el siguiente comando:

`dotnet add package Microsoft.CognitiveServices.Speech`

Para instalar el paquete de los servicios cognitivos de Speech que contiene SpeakerRecognition.
